name: ctrim_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.8.0+27 # iOS
# version: 0.8.0+24 # Android

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  add_2_calendar: 
  avatar_stack: 
  cloud_firestore: 
  cloud_functions: 
  firebase_analytics: 
  firebase_auth: 
  firebase_core: 
  firebase_messaging: 
  firebase_messaging_web: 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_quill:
  http: 
  intl: 
  package_info_plus: 
  path_provider: 
  photo_view: 
  provider:
  shared_preferences: 
  url_launcher: 
  video_player:
  gal: ^2.3.0
  gal_linux: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/info/testimonials/
    - assets/info/ctrim_info/
    - assets/info/churches/
    - assets/personal/
