// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqZuLrFFe8IB3s-eNt_wNhev__jw9-sj8',
    appId: '1:92089281469:web:4b511a3216878d527680d4',
    messagingSenderId: '92089281469',
    projectId: 'ctrim-8b49b',
    authDomain: 'ctrim-8b49b.firebaseapp.com',
    storageBucket: 'ctrim-8b49b.appspot.com',
    measurementId: 'G-12R3WV90ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrAaUNgrU0FjWe-tfYj8eAHls-TDmQ0A',
    appId: '1:92089281469:android:9470135a46831adf7680d4',
    messagingSenderId: '92089281469',
    projectId: 'ctrim-8b49b',
    storageBucket: 'ctrim-8b49b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsy5v3NS7xafvjk-v25QtKHheHlMCQVis',
    appId: '1:92089281469:ios:45c653aae9e0ec697680d4',
    messagingSenderId: '92089281469',
    projectId: 'ctrim-8b49b',
    storageBucket: 'ctrim-8b49b.appspot.com',
    androidClientId: '92089281469-rkgm72ihoquo6pfrsptsf0unmdu8kdkc.apps.googleusercontent.com',
    iosClientId: '92089281469-i1faceuc2ein3c0kbmoel8cfd8d1plpr.apps.googleusercontent.com',
    iosBundleId: 'com.ctrim.app',
  );
}
